spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  hikari:
    connection-timeout: 30000
    maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /

server:
  port: 8700
  servlet:
    context-path: /resume

logging:
  level:
    com.zaxxer.hikari: ERROR  # 🔹 Fixed indentation
